### ISSUE TITLE
Compilation Guide

### ISSUE THREAD

**Issue by nekiro** [whiteblXK/ObjectBuilder#1]
Hi, as I see you succesfully compiled object builder, what about creating compiling guide here in "wiki" board? It would help develop new things for custom servers.
Great work with this repo too.

**Comment by punkice3407** [comment]
Hi, no problem, will add later.

Edit:
Okay, tutorial can be found on wiki :)

**Comment by nekiro** [comment]
I didn't yet test it, but thanks a lot, will help many for sure!
