### ISSUE TITLE
Password Visual Code

### ISSUE THREAD

**Issue by nociambergmann** [whiteblXK/ObjectBuilder#17]
I can't enter the password

![image](https://user-images.githubusercontent.com/96496040/175828907-fa586c7a-77be-4a55-ba10-e6c852f77dc9.png)

**Comment by Luury** [comment]
I had the same problem, but I solved it by uninstalling the recent version of Java and installing an old version (Java SE Runtime Environment 8).

You can test using:
`adt -certificate -cn YOURNAME 2048-RSA object_builder.p12 123`
And after:
`adt -checkstore -storetype pkcs12 -keystore object_builder.p12 -storepass 123`

In `C:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0\bin`

Can close the issue.

**Comment by punkice3407** [comment]
The password is hidden for security, you need to write in this invisible space
