### ISSUE TITLE
reset/apply frames to all

### ISSUE THREAD

**Issue by elewental** [whiteblXK/ObjectBuilder#5]
It would be nice if there is some buttons for this:
- to reset all frames to initial param, in the selected object
- to apply current param to the other frames, in the selected object
- to apply the same frames to all animated objects in the client.

![image](https://user-images.githubusercontent.com/52132367/155870815-d7da09fa-abdc-461d-87e4-78a41414e0d9.png)
![image](https://user-images.githubusercontent.com/52132367/155872500-e60459f2-3e60-4a23-8560-1fe0a2b39ae3.png)

**Comment by elewental** [comment]
- add it as initial preference?
![image](https://user-images.githubusercontent.com/52132367/155872641-84117be0-487b-4b9f-877f-2d13290f929d.png)

**Comment by punkice3407** [comment]
I've added your suggestion

You can check these options in dev version
[ObjectBuilder_0_5_5-dev.zip](https://github.com/whiteblXK/ObjectBuilder/files/8148698/ObjectBuilder_0_5_5-dev.zip)

![image](https://i.imgur.com/oMmebwH.png)
![image](https://i.imgur.com/LbxSbbt.png)
![image](https://i.imgur.com/YLq6Eog.png)
